### ISSUE TITLE
Remove "stat.moneycontrol.co.in" from blocklist.

### ISSUE THREAD

**Issue by Rexadev** [anudeepND/blacklist#174] opened 2021-09-23 06:03 UTC
<div align="center">  
  <img width="280" height="70" src="https://raw.githubusercontent.com/anudeepND/blacklist/master/images/blacklist-logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

```
moneycontrol.co.in
```
<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
stat.moneycontrol.co.in
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail:

**Comment by spirillen** [comment] 2021-09-23 16:56
why? do you think this should be removed?

**Comment by Rexadev** [comment] 2021-09-24 05:40
> why? do you think this should be removed?

Some things dont properly load and are not aligned

**Comment by anudeepND** [comment] 2021-12-18 07:36
@Rexadev  @spirillen we had a similar issue with Moneycontrol, which was fixed in https://github.com/anudeepND/blacklist/issues/82 which I fixed by removing:
```
stat1.moneycontrol.com	
stat2.moneycontrol.com	
stat3.moneycontrol.com	
stat4.moneycontrol.com
```

And I couldn't find `stat.moneycontrol.co.in` in my logs while browsing the website and all the features such as charts, live chat, stock prices etc are working fine. Can you please provide more information @Rexadev ?

**Comment by Rexadev** [comment] 2021-12-18 08:48
> @Rexadev @spirillen we had a similar issue with Moneycontrol, which was fixed in #82 which I fixed by removing:
> 
> ```
> stat1.moneycontrol.com	
> stat2.moneycontrol.com	
> stat3.moneycontrol.com	
> stat4.moneycontrol.com
> ```
> 
> And I couldn't find `stat.moneycontrol.co.in` in my logs while browsing the website and all the features such as charts, live chat, stock prices etc are working fine. Can you please provide more information @Rexadev ?

Sort feature breaks and table is mis-aligned

**Comment by anudeepND** [comment] 2021-12-18 09:03
Sorry, I couldn't reproduce the issue can you post some screenshots?

> you are using .com and i suggested .co.in

`stat.moneycontrol.co.in` is not in my logs and I could not find it in dev console

**Closed** 2022-03-20 07:10 UTC
Labels: Help wanted, Investigating
